# Generated by Django 5.1.2 on 2024-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_first_name_user_last_name_user_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport',
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
